import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Tree News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body style={{ fontFamily: "IranYekan" }}>{children}</body>
    </html>
  );
}
