import SidebarAdmin from "@/src/containers/Dashborad/sidebaradmin/SidebarAdmin";
import TopDashboard from "@/src/containers/Dashborad/sidebaradmin/TopDashboard";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Tree News",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <body className="bg-[#f2f2f2]" style={{ fontFamily: "IranYekan" }}>
        <div
          suppressHydrationWarning={true}
          className="w-full h-[100vh] flex overflow-visible flex-row"
        >
          <SidebarAdmin />
          <div className="w-[79.9305555555555%] h-fit  mx-auto mt-6">
            <TopDashboard />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
